# Generated by Django 3.2 on 2021-06-08 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='用户表',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('用户名', models.CharField(db_column='用户名', max_length=20, unique=True, verbose_name='用户名')),
                ('密码', models.CharField(db_column='密码', max_length=128, verbose_name='密码')),
                ('用户类型', models.PositiveIntegerField(choices=[(1, '管理员'), (2, '教师'), (3, '学生')], db_column='用户类型', default='学生', verbose_name='用户类型')),
                ('性别', models.PositiveIntegerField(choices=[(1, '男'), (2, '女')], db_column='性别', default='男', verbose_name='性别')),
                ('真实姓名', models.CharField(blank=True, db_column='真实姓名', db_index=True, max_length=30, null=True, verbose_name='真实姓名')),
                ('学号', models.CharField(blank=True, max_length=10, null=True)),
                ('手机号', models.CharField(blank=True, db_column='手机号', max_length=11, null=True, verbose_name='手机号')),
                ('描述', models.CharField(blank=True, db_column='描述', max_length=1024, null=True, verbose_name='描述')),
                ('注册时间', models.DateTimeField(auto_now_add=True, db_column='注册时间', verbose_name='注册时间')),
                ('最后登录时间', models.DateTimeField(blank=True, db_column='最后登录时间', null=True, verbose_name='最后登录时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': '用户表',
                'ordering': ['注册时间'],
            },
        ),
        migrations.CreateModel(
            name='校园通知表',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('通知标题', models.CharField(blank=True, db_column='通知标题', max_length=1024, null=True, verbose_name='通知标题')),
                ('通知内容', models.TextField(blank=True, db_column='通知内容', null=True, verbose_name='通知内容')),
                ('发布时间', models.DateTimeField(auto_now=True, db_column='发布时间', verbose_name='发布时间')),
                ('发布人', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='通知作者', to='cimp.用户表', verbose_name='发布人')),
            ],
            options={
                'verbose_name': '校园通知',
                'verbose_name_plural': '校园通知',
                'db_table': '校园通知表',
                'ordering': ['发布时间'],
            },
        ),
        migrations.CreateModel(
            name='校园新闻表',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('新闻标题', models.CharField(blank=True, db_column='新闻标题', max_length=1024, null=True, verbose_name='新闻标题')),
                ('新闻内容', models.TextField(blank=True, db_column='新闻内容', null=True, verbose_name='新闻内容')),
                ('发布时间', models.DateTimeField(auto_now_add=True, db_column='发布时间', verbose_name='发布时间')),
                ('最后修改时间', models.DateTimeField(auto_now=True, db_column='最后修改时间', verbose_name='最后修改时间')),
                ('发布人', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='新闻作者', to='cimp.用户表', verbose_name='发布人')),
            ],
            options={
                'verbose_name': '校园新闻',
                'verbose_name_plural': '校园新闻',
                'db_table': '校园新闻表',
                'ordering': ['发布时间'],
            },
        ),
    ]
