# Generated by Django 3.2 on 2021-06-09 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cimp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='校园新闻表',
            options={'ordering': ['发布时间']},
        ),
        migrations.AlterModelOptions(
            name='校园通知表',
            options={'ordering': ['发布时间']},
        ),
        migrations.AlterModelOptions(
            name='用户表',
            options={'ordering': ['注册时间']},
        ),
        migrations.AlterField(
            model_name='校园新闻表',
            name='发布人',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='新闻作者', to='cimp.用户表'),
        ),
        migrations.AlterField(
            model_name='校园新闻表',
            name='发布时间',
            field=models.DateTimeField(auto_now_add=True, db_column='发布时间'),
        ),
        migrations.AlterField(
            model_name='校园新闻表',
            name='新闻内容',
            field=models.TextField(blank=True, db_column='新闻内容', null=True),
        ),
        migrations.AlterField(
            model_name='校园新闻表',
            name='新闻标题',
            field=models.CharField(blank=True, db_column='新闻标题', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='校园新闻表',
            name='最后修改时间',
            field=models.DateTimeField(auto_now=True, db_column='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='校园通知表',
            name='发布人',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='通知作者', to='cimp.用户表'),
        ),
        migrations.AlterField(
            model_name='校园通知表',
            name='发布时间',
            field=models.DateTimeField(auto_now=True, db_column='发布时间'),
        ),
        migrations.AlterField(
            model_name='校园通知表',
            name='通知内容',
            field=models.TextField(blank=True, db_column='通知内容', null=True),
        ),
        migrations.AlterField(
            model_name='校园通知表',
            name='通知标题',
            field=models.CharField(blank=True, db_column='通知标题', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='用户表',
            name='密码',
            field=models.CharField(db_column='密码', max_length=128),
        ),
        migrations.AlterField(
            model_name='用户表',
            name='性别',
            field=models.PositiveIntegerField(choices=[(1, '男'), (2, '女')], db_column='性别', default='男'),
        ),
        migrations.AlterField(
            model_name='用户表',
            name='手机号',
            field=models.CharField(blank=True, db_column='手机号', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='用户表',
            name='描述',
            field=models.CharField(blank=True, db_column='描述', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='用户表',
            name='最后登录时间',
            field=models.DateTimeField(blank=True, db_column='最后登录时间', null=True),
        ),
        migrations.AlterField(
            model_name='用户表',
            name='注册时间',
            field=models.DateTimeField(auto_now_add=True, db_column='注册时间'),
        ),
        migrations.AlterField(
            model_name='用户表',
            name='用户名',
            field=models.CharField(db_column='用户名', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='用户表',
            name='用户类型',
            field=models.PositiveIntegerField(choices=[(1, '管理员'), (2, '教师'), (3, '学生')], db_column='用户类型', default='学生'),
        ),
        migrations.AlterField(
            model_name='用户表',
            name='真实姓名',
            field=models.CharField(blank=True, db_column='真实姓名', db_index=True, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='学生论文表',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('论文主题', models.CharField(blank=True, db_column='论文主题', max_length=1024, null=True)),
                ('主题描述', models.TextField(blank=True, db_column='主题描述', null=True)),
                ('论文内容', models.TextField(blank=True, db_column='论文内容', null=True)),
                ('发布时间', models.DateTimeField(auto_now=True, db_column='发布时间')),
                ('审核状态', models.IntegerField(choices=[(0, '主题未创建'), (1, '主题创建'), (2, '主题未通过'), (3, '主题通过'), (4, '论文创建'), (5, '论文未通过'), (6, '论文通过')], db_column='审核状态', default='主题未创建')),
                ('论文评分', models.IntegerField(db_column='论文评分', default=0)),
                ('导师', models.ForeignKey(limit_choices_to={'用户类型': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='Mentor', to='cimp.用户表')),
                ('论文作者', models.OneToOneField(limit_choices_to={'用户类型': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='ArticleAuthor', to='cimp.用户表')),
            ],
            options={
                'db_table': '学生论文表',
                'ordering': ['发布时间'],
            },
        ),
    ]
